#!/usr/bin/env python3
"""Condition C5: deterministic rule-based transpiler baseline (Protocol Amendment AD-02).

A no-LLM, no-network control that measures how much of LegacyCRM-Bench is mechanically
saturable from the legacy artifacts alone. For each case it can handle, it generates the
case's deliverable files under <out-root>/<CASE_ID>/ using ONLY:

  * the case's legacy/ artifacts (parsed genuinely: VRL rule files, workflow XML,
    INI/CFG/CSV configuration), and
  * generic, family-level generation rules (one generator per artifact/interface family).

Honesty constraints (enforced by construction):
  * No per-case hard-coded expected values; no reading of reference/, tests/, or
    GROUND_TRUTH.md. The only non-legacy input is target_spec.md, read exclusively to
    lift the required interface (deliverable file names and function signatures) —
    legitimate, since real migrations are given their target interface.
  * A case whose bespoke interface cannot be produced mechanically is SKIPPED
    (no output emitted); skips are recorded as data in the results _meta line.

Generators implemented (artifact family -> deliverable):
  vrl_validate    legacy/*.vrl              -> migrated.py  (VAL-family validate())
  workflow_engine legacy/<workflow>.xml     -> migrated.py  (WFL-family fire())
  batch_schedule  legacy/batch_jobs.cfg     -> migrated.py + schedule.json (BAT-01 family)
  endpoints_json  legacy/endpoints.ini      -> endpoints.json (INT-01 family)
  enums_json      legacy/data_dictionary.csv-> enums.json  (CFG-01 family)
  workflows_json  legacy/workflows.xml      -> workflows.json (CFG-03 family)
  audit_cfg       legacy/audit_config.cfg   -> migrated.py  (AUD-01 family)

Usage:
  python transpiler_c5.py --out-root <dir> [--no-eval]

Results are written to 05_results/c5_transpiler_baseline.jsonl (a _meta header line,
then one line per attempted case), via the sandboxed evaluator (runner/sandbox.py).
Stdlib only; deterministic.
"""
import argparse
import configparser
import csv
import io
import json
import re
import sys
import time
import xml.etree.ElementTree as ET
from pathlib import Path

V1 = Path(__file__).resolve().parent.parent.parent
CASES_ROOT = V1 / "02_benchmark_dataset" / "cases"
RESULTS_PATH = V1 / "05_results" / "c5_transpiler_baseline.jsonl"

GENERATED_HEADER = (
    '"""Auto-generated by the LegacyCRM-Bench C5 rule-based transpiler (no LLM).\n'
    "Derived mechanically from the case's legacy/ artifacts under documented\n"
    'Meridian CRM 4.2 semantics (SYSTEM_OVERVIEW.md). Stdlib only; deterministic."""\n'
)

# --------------------------------------------------------------------------------------
# Generic VRL expression runtime, embedded verbatim into generated modules.
# Implements the documented VRL semantics (SYSTEM_OVERVIEW.md section 2):
# comparisons, arithmetic, AND/OR/NOT, LEN/UPPER/SUBSTR/NVL/TODAY/LOOKUP,
# empty-string->0 numeric coercion, lexicographic YYYYMMDD dates with the 00000000
# sentinel (ordering vs sentinel is FALSE; equality/inequality to the literal works),
# OLD.<col> pre-images (empty on INSERT), LOOKUP over live rows only (DEL_FLG != 'Y').
# --------------------------------------------------------------------------------------
VRL_RUNTIME = r'''
import re as _re

_VRL_TOKEN = _re.compile(r"""\s*(?:
      (?P<num>\d+(?:\.\d+)?)
    | (?P<str>'[^']*')
    | (?P<id>[A-Za-z_][A-Za-z0-9_]*(?:\.[A-Za-z_][A-Za-z0-9_]*)?)
    | (?P<op><=|>=|<>|[<>=+\-*/(),])
    )""", _re.X)

_SENTINEL = "00000000"


def _vrl_tokenize(src):
    toks, pos = [], 0
    while pos < len(src):
        m = _VRL_TOKEN.match(src, pos)
        if not m:
            if src[pos:].strip() == "":
                break
            raise ValueError("VRL tokenize error at: %r" % src[pos:pos + 20])
        pos = m.end()
        if m.lastgroup == "num":
            toks.append(("num", float(m.group("num"))))
        elif m.lastgroup == "str":
            toks.append(("str", m.group("str")[1:-1]))
        elif m.lastgroup == "id":
            word = m.group("id")
            if word.upper() in ("AND", "OR", "NOT"):
                toks.append(("kw", word.upper()))
            else:
                toks.append(("id", word))
        else:
            toks.append(("op", m.group("op")))
    toks.append(("end", None))
    return toks


class _VrlParser:
    def __init__(self, toks):
        self.toks = toks
        self.i = 0

    def peek(self):
        return self.toks[self.i]

    def next(self):
        t = self.toks[self.i]
        self.i += 1
        return t

    def expect_op(self, op):
        t = self.next()
        if t != ("op", op):
            raise ValueError("VRL parse error: expected %r, got %r" % (op, t))

    def parse(self):
        node = self.parse_or()
        if self.peek()[0] != "end":
            raise ValueError("VRL parse error: trailing tokens %r" % (self.peek(),))
        return node

    def parse_or(self):
        node = self.parse_and()
        while self.peek() == ("kw", "OR"):
            self.next()
            node = ("or", node, self.parse_and())
        return node

    def parse_and(self):
        node = self.parse_not()
        while self.peek() == ("kw", "AND"):
            self.next()
            node = ("and", node, self.parse_not())
        return node

    def parse_not(self):
        if self.peek() == ("kw", "NOT"):
            self.next()
            return ("not", self.parse_not())
        return self.parse_cmp()

    def parse_cmp(self):
        node = self.parse_add()
        kind, val = self.peek()
        if kind == "op" and val in ("=", "<>", "<", "<=", ">", ">="):
            self.next()
            node = ("cmp", val, node, self.parse_add())
        return node

    def parse_add(self):
        node = self.parse_mul()
        while self.peek()[0] == "op" and self.peek()[1] in ("+", "-"):
            op = self.next()[1]
            node = ("bin", op, node, self.parse_mul())
        return node

    def parse_mul(self):
        node = self.parse_unary()
        while self.peek()[0] == "op" and self.peek()[1] in ("*", "/"):
            op = self.next()[1]
            node = ("bin", op, node, self.parse_unary())
        return node

    def parse_unary(self):
        if self.peek() == ("op", "-"):
            self.next()
            return ("neg", self.parse_unary())
        return self.parse_primary()

    def parse_primary(self):
        kind, val = self.next()
        if kind == "num":
            return ("num", val)
        if kind == "str":
            return ("str", val)
        if kind == "op" and val == "(":
            node = self.parse_or()
            self.expect_op(")")
            return node
        if kind == "id":
            if self.peek() == ("op", "("):
                self.next()
                args = []
                if self.peek() != ("op", ")"):
                    args.append(self.parse_or())
                    while self.peek() == ("op", ","):
                        self.next()
                        args.append(self.parse_or())
                self.expect_op(")")
                return ("call", val.upper(), args)
            if val.upper().startswith("OLD."):
                return ("old", val.split(".", 1)[1])
            return ("field", val)
        raise ValueError("VRL parse error at token (%r, %r)" % (kind, val))


def _vrl_parse_expr(src):
    return _VrlParser(_vrl_tokenize(src)).parse()


def _num(v):
    if isinstance(v, bool):
        return 1.0 if v else 0.0
    if isinstance(v, (int, float)):
        return float(v)
    s = str(v).strip()
    if s == "":
        return 0.0
    try:
        return float(s)
    except ValueError:
        return 0.0


def _is_number(v):
    return isinstance(v, (int, float)) and not isinstance(v, bool)


def _truthy(v):
    if isinstance(v, bool):
        return v
    if isinstance(v, (int, float)):
        return v != 0
    return str(v) != ""


def _cmp(op, a, b):
    if op in ("<", "<=", ">", ">="):
        if isinstance(a, str) and isinstance(b, str) and not _is_number(a) and not _is_number(b):
            # date/string ordering: lexicographic, sentinel never orders
            if a == _SENTINEL or b == _SENTINEL:
                return False
            la, lb = a, b
        else:
            la, lb = _num(a), _num(b)
        if op == "<":
            return la < lb
        if op == "<=":
            return la <= lb
        if op == ">":
            return la > lb
        return la >= lb
    # = / <>
    if _is_number(a) or _is_number(b):
        eq = _num(a) == _num(b)
    else:
        eq = str(a) == str(b)
    return eq if op == "=" else not eq


def _name_of(node):
    if node[0] == "field":
        return node[1]
    if node[0] == "old":
        return "OLD." + node[1]
    if node[0] == "str":
        return node[1]
    raise ValueError("LOOKUP argument must be a column/table name, got %r" % (node,))


def _vrl_eval(node, env):
    kind = node[0]
    if kind == "num":
        return node[1]
    if kind == "str":
        return node[1]
    if kind == "field":
        rec = env.get("record") or {}
        v = rec.get(node[1], "")
        return "" if v is None else v
    if kind == "old":
        old = env.get("old")
        if not old:
            return ""
        v = old.get(node[1], "")
        return "" if v is None else v
    if kind == "and":
        return _truthy(_vrl_eval(node[1], env)) and _truthy(_vrl_eval(node[2], env))
    if kind == "or":
        return _truthy(_vrl_eval(node[1], env)) or _truthy(_vrl_eval(node[2], env))
    if kind == "not":
        return not _truthy(_vrl_eval(node[1], env))
    if kind == "cmp":
        return _cmp(node[1], _vrl_eval(node[2], env), _vrl_eval(node[3], env))
    if kind == "neg":
        return -_num(_vrl_eval(node[1], env))
    if kind == "bin":
        a, b = _num(_vrl_eval(node[2], env)), _num(_vrl_eval(node[3], env))
        if node[1] == "+":
            return a + b
        if node[1] == "-":
            return a - b
        if node[1] == "*":
            return a * b
        return 0.0 if b == 0 else a / b  # documented legacy quirk: div by zero -> 0
    if kind == "call":
        fn, args = node[1], node[2]
        if fn == "LEN":
            v = _vrl_eval(args[0], env)
            return float(len(v if isinstance(v, str) else str(v)))
        if fn == "UPPER":
            return str(_vrl_eval(args[0], env)).upper()
        if fn == "SUBSTR":
            s = str(_vrl_eval(args[0], env))
            start = int(_num(_vrl_eval(args[1], env)))
            ln = int(_num(_vrl_eval(args[2], env)))
            return s[start - 1:start - 1 + ln]
        if fn == "NVL":
            v = _vrl_eval(args[0], env)
            if v is None or (isinstance(v, str) and v == ""):
                return _vrl_eval(args[1], env)
            return v
        if fn == "TODAY":
            return env.get("today") or ""
        if fn == "LOOKUP":
            tables = env.get("tables") or {}
            tbl = tables.get(_name_of(args[0])) or []
            key_col = _name_of(args[1])
            key_val = _vrl_eval(args[2], env)
            out_col = _name_of(args[3])
            for row in tbl:
                if row.get("DEL_FLG", "") == "Y":
                    continue  # LOOKUP sees live rows only
                if str(row.get(key_col, "")) == str(key_val):
                    v = row.get(out_col, "")
                    return "" if v is None else v
            return ""
        raise ValueError("Unknown VRL function %r" % fn)
    raise ValueError("Bad VRL node %r" % (node,))


_VRL_RULE_LINE = _re.compile(
    r'^RULE\s+(?P<id>\S+)\s+ON\s+(?P<table>\S+)\s+WHEN\s+(?P<events>[A-Z, ]+?)\s*:\s*'
    r'(?P<expr>.*?)\s+ELSE\s+ERROR\s+(?P<code>\S+)\s+"(?P<msg>[^"]*)"'
    r'(?:\s+SEVERITY\s+(?P<sev>BLOCK|WARN))?\s*$')


def _parse_vrl(text):
    rules = []
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        m = _VRL_RULE_LINE.match(line)
        if not m:
            raise ValueError("Unparseable VRL line: %r" % line)
        rules.append({
            "id": m.group("id"),
            "table": m.group("table"),
            "events": tuple(e.strip() for e in m.group("events").split(",")),
            "ast": _vrl_parse_expr(m.group("expr")),
            "code": m.group("code"),
            "message": m.group("msg"),
            "severity": m.group("sev") or "BLOCK",
        })
    return rules


def _vrl_run(rules, record, old, event, today, tables, table):
    errors = []
    env = {"record": record or {}, "old": old if event == "UPDATE" else None,
           "today": today, "tables": tables}
    for r in rules:
        if event not in r["events"]:
            continue
        if table is not None and r["table"] != table:
            continue
        if not _truthy(_vrl_eval(r["ast"], env)):
            errors.append({"code": r["code"], "message": r["message"],
                           "severity": r["severity"]})
    return errors


def is_blocked(errors):
    return any(e.get("severity") == "BLOCK" for e in errors)
'''

# Workflow-engine runtime (appended after VRL_RUNTIME in WFL-family modules).
WF_RUNTIME = r'''
import xml.etree.ElementTree as _ET


def _wf_parse(xml_text):
    root = _ET.fromstring(xml_text.lstrip())
    wf = root if root.tag == "workflow" else root.find(".//workflow")
    transitions = []
    for tr in wf.findall("transition"):
        guard_el = tr.find("guard")
        guard_ast = None
        if guard_el is not None and guard_el.text and guard_el.text.strip():
            guard_ast = _vrl_parse_expr(guard_el.text.strip())
        actions = []
        acts_el = tr.find("actions")
        if acts_el is not None:
            for a in acts_el:
                if a.tag == "set":
                    actions.append(("set", a.get("field"), a.get("value")))
                elif a.tag == "audit":
                    actions.append(("audit", a.get("code")))
                elif a.tag == "notify":
                    actions.append(("notify", a.get("template")))
        transitions.append({"from": tr.get("from"), "to": tr.get("to"),
                            "event": tr.get("event"), "guard": guard_ast,
                            "actions": actions})
    return transitions


def _wf_fire(transitions, state, event, record, tables):
    record = record or {}
    for tr in transitions:  # first match in document order wins
        if tr["from"] != state or tr["event"] != event:
            continue
        if tr["guard"] is not None:
            env = {"record": record, "old": None, "today": "", "tables": tables}
            if not _truthy(_vrl_eval(tr["guard"], env)):
                continue
        new_rec = dict(record)
        audits, notifies = [], []
        for act in tr["actions"]:  # <set> applies after the state change, in order
            if act[0] == "set":
                value = act[2]
                if isinstance(value, str) and value.startswith("="):
                    env = {"record": new_rec, "old": None, "today": "", "tables": tables}
                    value = _vrl_eval(_vrl_parse_expr(value[1:]), env)
                new_rec[act[1]] = value
            elif act[0] == "audit":
                audits.append(act[1])
            else:
                notifies.append(act[1])
        return {"state": tr["to"], "record": new_rec, "audits": audits,
                "notifies": notifies, "matched": True}
    return {"state": state, "record": dict(record), "audits": ["WF_NOMATCH"],
            "notifies": [], "matched": False}
'''


# --------------------------------------------------------------------------------------
# Interface lifting: read target_spec.md ONLY to extract required function signatures.
# --------------------------------------------------------------------------------------
def lift_signature(spec_text: str, func_name: str):
    """Return (def_line, param_names) for the required interface function, or None."""
    m = re.search(r"def\s+%s\s*\(([^)]*)\)\s*(->\s*[^:]+)?:" % re.escape(func_name),
                  spec_text, re.S)
    if not m:
        return None
    params_raw = re.sub(r"\s+", " ", m.group(1)).strip()
    ret = re.sub(r"\s+", " ", (m.group(2) or "")).strip()
    def_line = "def %s(%s)%s:" % (func_name, params_raw, (" " + ret) if ret else "")
    names = []
    for part in params_raw.split(","):
        name = part.split(":")[0].split("=")[0].strip()
        if name:
            names.append(name)
    return def_line, names


def embed_text(name: str, text: str) -> str:
    if "'''" in text:
        raise ValueError("artifact contains triple quotes; cannot embed")
    return "%s = r'''\n%s'''\n" % (name, text if text.endswith("\n") else text + "\n")


# --------------------------------------------------------------------------------------
# Family generators. Each takes (case_dir, spec_text, deliverables) and returns
# {filename: content} or None if it cannot handle the case mechanically.
# --------------------------------------------------------------------------------------
def gen_vrl_validate(case_dir, spec_text, deliverables):
    vrl_files = sorted((case_dir / "legacy").glob("*.vrl"))
    if deliverables != ["migrated.py"] or len(vrl_files) != 1:
        return None
    sig = lift_signature(spec_text, "validate")
    if not sig:
        return None
    def_line, params = sig
    vrl_text = vrl_files[0].read_text()
    if "tables" in params and "table" in params:
        body = '    return _vrl_run(_RULES, record, old, event, "", tables, table)\n'
    elif "today" in params:
        body = "    return _vrl_run(_RULES, record, old, event, today, None, None)\n"
    else:
        return None
    src = (GENERATED_HEADER + embed_text("_VRL_SOURCE", vrl_text) + VRL_RUNTIME
           + "\n_RULES = _parse_vrl(_VRL_SOURCE)\n\n\n" + def_line + "\n" + body)
    return {"migrated.py": src}


def gen_workflow_engine(case_dir, spec_text, deliverables):
    xml_files = sorted((case_dir / "legacy").glob("*.xml"))
    if deliverables != ["migrated.py"] or len(xml_files) != 1:
        return None
    sig = lift_signature(spec_text, "fire")
    if not sig:
        return None
    def_line, params = sig
    xml_text = xml_files[0].read_text()
    tables_arg = "tables" if "tables" in params else "None"
    body = "    return _wf_fire(_TRANSITIONS, state, event, record, %s)\n" % tables_arg
    src = (GENERATED_HEADER + embed_text("_WORKFLOW_XML", xml_text) + VRL_RUNTIME
           + WF_RUNTIME + "\n_TRANSITIONS = _wf_parse(_WORKFLOW_XML)\n\n\n"
           + def_line + "\n" + body)
    return {"migrated.py": src}


BATCH_PARSER_SRC = r'''
import re as _re

_JOB_LINE = _re.compile(
    r"^JOB\s+(?P<name>\S+)\s+AT\s+(?P<at>\d{2}:\d{2})\s+RUN\s+(?P<script>\S+)"
    r"(?:\s+ON_ERROR\s+(?P<clause>\S+))?\s*$")


def parse_schedule(cfg_text: str) -> list[dict]:
    jobs = []
    for line in cfg_text.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        m = _JOB_LINE.match(line)
        if not m:
            continue
        clause = m.group("clause")
        if clause is None:
            # absent clause -> strictest policy (sequential nightly chain)
            policy, retries = "ABORT", 0
        elif clause.upper().startswith("RETRY:"):
            policy, retries = "RETRY", int(clause.split(":", 1)[1])
        else:
            policy, retries = clause.upper(), 0
        jobs.append({"name": m.group("name"), "at": m.group("at"),
                     "script": m.group("script"),
                     "on_error": {"policy": policy, "retries": retries}})
    return jobs
'''


def gen_batch_schedule(case_dir, spec_text, deliverables):
    cfg = case_dir / "legacy" / "batch_jobs.cfg"
    if not cfg.is_file() or "schedule.json" not in deliverables:
        return None
    if not lift_signature(spec_text, "parse_schedule"):
        return None
    module_src = GENERATED_HEADER + BATCH_PARSER_SRC
    ns = {}
    exec(compile(module_src, "migrated.py", "exec"), ns)
    schedule = ns["parse_schedule"](cfg.read_text())
    return {"migrated.py": module_src,
            "schedule.json": json.dumps(schedule, indent=2) + "\n"}


def gen_endpoints_json(case_dir, spec_text, deliverables):
    ini = case_dir / "legacy" / "endpoints.ini"
    if not ini.is_file() or deliverables != ["endpoints.json"]:
        return None
    cp = configparser.ConfigParser(interpolation=None)
    cp.read_string(ini.read_text())
    out = {}
    for section in cp.sections():
        s = cp[section]
        auth_raw = s.get("auth", "none").strip()
        if auth_raw == "none":
            auth = {"type": "none", "secret_ref": None}
        else:
            typ, _, ref = auth_raw.partition(":")
            auth = {"type": typ, "secret_ref": ref}  # vault reference kept verbatim
        out[section] = {
            "url": s.get("url", "").strip(),
            "auth": auth,
            "retry": int(s.get("retry", "0")),
            "timeout_ms": int(s.get("timeout_ms", "0")),
            "payload": s.get("payload", "").strip(),
            "layout": s.get("layout", "").strip() if "layout" in s else None,
        }
    return {"endpoints.json": json.dumps(out, indent=2) + "\n"}


# Generic enum-detection rules for data-dictionary MEANING fields:
#   an enumerated code table is a MEANING whose ';'-separated segments are ALL
#   short-code '=' label pairs (codes of 1-3 alphanumerics, or the storage-default
#   marker 'blank' which is dropped), with at least two real codes remaining.
#   Parenthesized operational annotations at the end of a label are stripped.
_ENUM_PAIR = re.compile(r"^([A-Za-z0-9]{1,3}|blank)=(.*)$")


def _meaning_to_enum(meaning: str):
    pairs = {}
    for seg in meaning.split(";"):
        seg = seg.strip()
        if not seg:
            continue
        m = _ENUM_PAIR.match(seg)
        if not m:
            return None  # free-text segment -> convention note, not an enum
        code, label = m.group(1), m.group(2).strip()
        if code == "blank":
            continue  # storage default, not a code
        label = re.sub(r"\([^)]*\)\s*$", "", label).strip()  # strip annotations
        pairs[code] = label
    if len(pairs) < 2:
        return None  # single Y-flag style booleans are not code tables
    return pairs


def gen_enums_json(case_dir, spec_text, deliverables):
    dd = case_dir / "legacy" / "data_dictionary.csv"
    if not dd.is_file() or deliverables != ["enums.json"]:
        return None
    out = {}
    with dd.open(newline="") as f:
        for row in csv.DictReader(f):
            if row.get("DICT_TYPE") != "COLUMN":
                continue
            enum = _meaning_to_enum(row.get("MEANING", ""))
            if enum is not None:
                out["%s.%s" % (row["TABLE_NM"], row["COL_NM"])] = enum
    return {"enums.json": json.dumps(out, indent=2) + "\n"}


def gen_workflows_json(case_dir, spec_text, deliverables):
    xml_path = case_dir / "legacy" / "workflows.xml"
    if not xml_path.is_file() or deliverables != ["workflows.json"]:
        return None
    root = ET.fromstring(xml_path.read_text())
    workflows = []
    for wf in root.findall("workflow"):
        states = []
        states_el = wf.find("states")
        for st in (states_el.findall("state") if states_el is not None else []):
            timers = [{"after_days": int(t.get("after_days")), "event": t.get("event")}
                      for t in st.findall("timer")]
            states.append({"code": st.get("code"),
                           "initial": st.get("initial") == "true",
                           "timers": timers})
        transitions = []
        for tr in wf.findall("transition"):
            guard_el = tr.find("guard")
            guard = None
            if guard_el is not None and guard_el.text is not None:
                guard = guard_el.text.strip()  # verbatim VRL (entity-decoded by ET)
            actions = []
            acts_el = tr.find("actions")
            if acts_el is not None:
                for a in acts_el:
                    if a.tag == "set":
                        actions.append({"type": "set", "field": a.get("field"),
                                        "value": a.get("value")})
                    elif a.tag == "audit":
                        actions.append({"type": "audit", "code": a.get("code")})
                    elif a.tag == "notify":
                        actions.append({"type": "notify", "template": a.get("template")})
            transitions.append({"from": tr.get("from"), "to": tr.get("to"),
                                "event": tr.get("event"), "guard": guard,
                                "actions": actions})
        workflows.append({"name": wf.get("name"), "entity": wf.get("entity"),
                          "state_field": wf.get("state_field"),
                          "states": states, "transitions": transitions})
    return {"workflows.json": json.dumps({"workflows": workflows}, indent=2) + "\n"}


AUDIT_PARSER_SRC = r'''
def audited_columns(cfg_text: str) -> dict[str, set[str]]:
    out: dict[str, set[str]] = {}
    for line in cfg_text.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        tokens = line.split()
        if len(tokens) == 3 and tokens[0] == "AUDIT":
            out.setdefault(tokens[1], set()).add(tokens[2])
    return out
'''


def gen_audit_cfg(case_dir, spec_text, deliverables):
    cfg = case_dir / "legacy" / "audit_config.cfg"
    if not cfg.is_file() or deliverables != ["migrated.py"]:
        return None
    if not lift_signature(spec_text, "audited_columns"):
        return None
    return {"migrated.py": GENERATED_HEADER + AUDIT_PARSER_SRC}


GENERATORS = [
    gen_vrl_validate,
    gen_workflow_engine,
    gen_batch_schedule,
    gen_endpoints_json,
    gen_enums_json,
    gen_workflows_json,
    gen_audit_cfg,
]


# --------------------------------------------------------------------------------------
# Driver
# --------------------------------------------------------------------------------------
def find_cases():
    cases = []
    for cj in sorted(CASES_ROOT.glob("*/*/case.json")):
        cases.append(cj.parent)
    return cases


def generate_all(out_root: Path):
    attempted, skipped = [], []
    for case_dir in find_cases():
        meta = json.loads((case_dir / "case.json").read_text())
        spec_text = (case_dir / "target_spec.md").read_text()
        deliverables = meta["deliverables"]
        produced = None
        for gen in GENERATORS:
            produced = gen(case_dir, spec_text, deliverables)
            if produced is not None:
                break
        if produced is None or set(produced) != set(deliverables):
            skipped.append(meta["id"])
            continue
        dest = out_root / meta["id"]
        dest.mkdir(parents=True, exist_ok=True)
        for fname, content in produced.items():
            (dest / fname).write_text(content)
        attempted.append((meta["id"], case_dir, dest))
    return attempted, skipped


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--out-root", required=True, help="directory for generated candidate solutions")
    ap.add_argument("--no-eval", action="store_true", help="generate only; skip sandboxed evaluation")
    args = ap.parse_args()
    out_root = Path(args.out_root).resolve()
    out_root.mkdir(parents=True, exist_ok=True)

    attempted, skipped = generate_all(out_root)
    print("C5 rule-based transpiler: generated %d candidates, skipped %d cases"
          % (len(attempted), len(skipped)))
    print("Skipped (bespoke interface, not mechanically derivable): %s"
          % (", ".join(skipped) if skipped else "none"))
    if args.no_eval:
        return

    sys.path.insert(0, str(Path(__file__).resolve().parent))
    from sandbox import run_sandboxed  # noqa: E402

    results = []
    for case_id, case_dir, sol_dir in attempted:
        res = run_sandboxed(case_dir, sol_dir)
        results.append(res)
        print("  %-7s %2d/%2d passed  all_passed=%s" %
              (case_id, res["num_passed"], res["num_tests_collected"], res["all_passed"]))

    meta_line = {"run_type": "c5_transpiler",
                 "timestamp_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
                 "cases_attempted": len(attempted),
                 "cases_skipped": len(skipped),
                 "skipped_ids": skipped}
    RESULTS_PATH.parent.mkdir(parents=True, exist_ok=True)
    with RESULTS_PATH.open("w") as f:
        f.write(json.dumps({"_meta": meta_line}) + "\n")
        for res in results:
            f.write(json.dumps(res) + "\n")

    print("\n%-8s %-10s %-6s %8s %10s" % ("case", "category", "diff", "passed", "all_passed"))
    for res in results:
        print("%-8s %-10s %-6s %5d/%-3d %10s" %
              (res["case_id"], res["category"], res["difficulty"],
               res["num_passed"], res["num_tests_collected"], res["all_passed"]))
    n_all = sum(1 for r in results if r["all_passed"])
    print("\nAttempted: %d  all-pass: %d  skipped: %d (%s)"
          % (len(results), n_all, len(skipped), ", ".join(skipped)))
    print("Results written to %s" % RESULTS_PATH)


if __name__ == "__main__":
    main()
