#!/usr/bin/env python3
"""Generate LaTeX table bodies and a numbers-macro file from the machine-generated CSVs.

Reads 06_figures_tables/T1..T3 CSVs (produced by aggregate.py) and writes:
  07_manuscript/generated/T1_composition.tex
  07_manuscript/generated/T2_validation.tex
  07_manuscript/generated/T3_mutation.tex
  07_manuscript/generated/numbers.tex   (\newcommand macros for every in-text number)
The manuscript inputs these files, so prose/table numbers cannot drift from raw results.
"""
import csv
from pathlib import Path

V1 = Path(__file__).resolve().parent.parent.parent
FT = V1 / "06_figures_tables"
GEN = V1 / "07_manuscript" / "generated"

PRETTY = {
    "schema_mapping": "Schema mapping", "validation_rules": "Validation rules",
    "workflows": "Workflows", "legacy_scripts": "Legacy scripts", "rbac": "RBAC",
    "integration": "Integration", "batch_processing": "Batch processing",
    "error_handling": "Error handling", "audit_logging": "Audit logging",
    "referential_integrity": "Referential integrity", "business_rules": "Business rules",
    "config_modernization": "Config.\\ modernization",
}


def rows_of(name):
    with open(FT / name, newline="") as f:
        return list(csv.DictReader(f))


def main():
    GEN.mkdir(parents=True, exist_ok=True)
    t1 = rows_of("T1_benchmark_composition.csv")
    t2 = rows_of("T2_groundtruth_validation.csv")
    t3 = rows_of("T3_mutation_sensitivity.csv")

    with open(GEN / "T1_composition.tex", "w") as f:
        for r in t1:
            cat = PRETTY.get(r["category"], r["category"]) if r["category"] != "TOTAL" else "\\textbf{Total}"
            bold = r["category"] == "TOTAL"
            if bold:
                f.write("\\midrule\n")
            cells = [cat, r["cases"], r["easy"], r["medium"], r["hard"], r["acceptance_tests"]]
            if bold:
                cells = [cells[0]] + [f"\\textbf{{{c}}}" for c in cells[1:]]
            f.write(" & ".join(cells) + " \\\\\n")
        # booktabs rules must live inside the input file (a rule directly after \input fails)
        f.write("\\bottomrule\n")

    t2map = {r["category"]: r for r in t2}
    t3map = {r["category"]: r for r in t3}
    with open(GEN / "T2_validation.tex", "w") as f:
        for r in t2:
            if r["category"] == "TOTAL":
                continue
            m = t3map.get(r["category"], {})
            f.write(" & ".join([
                PRETTY.get(r["category"], r["category"]),
                f"{r['reference_tests_passed']}/{r['reference_tests_total']}",
                f"{r['null_tests_passed']}/{r['null_tests_total']}",
                m.get("mutants", "--"), m.get("killed", "--"),
                m.get("kill_rate_pct", "--"),
            ]) + " \\\\\n")
        tt2, tt3 = t2map["TOTAL"], t3map.get("TOTAL", {})
        f.write("\\midrule\n")
        f.write(" & ".join([
            "\\textbf{Total}",
            f"\\textbf{{{tt2['reference_tests_passed']}/{tt2['reference_tests_total']}}}",
            f"\\textbf{{{tt2['null_tests_passed']}/{tt2['null_tests_total']}}}",
            f"\\textbf{{{tt3.get('mutants','--')}}}", f"\\textbf{{{tt3.get('killed','--')}}}",
            f"\\textbf{{{tt3.get('kill_rate_pct','--')}}}",
        ]) + " \\\\\n")
        f.write("\\bottomrule\n")

    tot1 = next(r for r in t1 if r["category"] == "TOTAL")
    tt2 = t2map["TOTAL"]
    tt3 = t3map.get("TOTAL", {})
    surv = 0
    surv_file = FT / "surviving_mutants.csv"
    if surv_file.is_file():
        surv = max(0, sum(1 for _ in open(surv_file)) - 1)
    # seed-data row count, computed from the actual CSVs (no hand-entered numbers in prose)
    seed_dir = V1 / "02_benchmark_dataset" / "legacy_system" / "seed_data"
    seed_rows = sum(max(0, sum(1 for _ in open(p)) - 1) for p in sorted(seed_dir.glob("*.csv")))
    # Wilson 95% CI for the mutation kill rate
    import math
    n = int(tt3.get("mutants", 0) or 0)
    k = int(tt3.get("killed", 0) or 0)
    ci_lo = ci_hi = 0.0
    if n:
        z = 1.959964
        ph = k / n
        den = 1 + z * z / n
        center = (ph + z * z / (2 * n)) / den
        half = z * math.sqrt(ph * (1 - ph) / n + z * z / (4 * n * n)) / den
        ci_lo, ci_hi = (center - half) * 100, (center + half) * 100
    with open(GEN / "numbers.tex", "w") as f:
        f.write("% auto-generated by make_tex_tables.py — do not edit\n")
        f.write(f"\\newcommand{{\\NumCases}}{{{tot1['cases']}}}\n")
        f.write(f"\\newcommand{{\\NumTests}}{{{tot1['acceptance_tests']}}}\n")
        f.write(f"\\newcommand{{\\NumEasy}}{{{tot1['easy']}}}\n")
        f.write(f"\\newcommand{{\\NumMedium}}{{{tot1['medium']}}}\n")
        f.write(f"\\newcommand{{\\NumHard}}{{{tot1['hard']}}}\n")
        f.write(f"\\newcommand{{\\RefPassed}}{{{tt2['reference_tests_passed']}}}\n")
        f.write(f"\\newcommand{{\\RefTotal}}{{{tt2['reference_tests_total']}}}\n")
        f.write(f"\\newcommand{{\\NullPassed}}{{{tt2['null_tests_passed']}}}\n")
        f.write(f"\\newcommand{{\\NumMutants}}{{{tt3.get('mutants','?')}}}\n")
        f.write(f"\\newcommand{{\\MutantsKilled}}{{{tt3.get('killed','?')}}}\n")
        f.write(f"\\newcommand{{\\KillRate}}{{{tt3.get('kill_rate_pct','?')}}}\n")
        f.write(f"\\newcommand{{\\SurvivingMutants}}{{{surv}}}\n")
        f.write(f"\\newcommand{{\\SeedRows}}{{{seed_rows}}}\n")
        f.write(f"\\newcommand{{\\KillRateCILo}}{{{ci_lo:.1f}}}\n")
        f.write(f"\\newcommand{{\\KillRateCIHi}}{{{ci_hi:.1f}}}\n")
    # ---- model-evaluation table + macros (from M1/M4/M5 + run ledger) ----
    m1_path = FT / "M1_case_allpass.csv"
    if m1_path.is_file():
        m1 = {(r["model"], r["condition"]): r for r in rows_of("M1_case_allpass.csv")}
        m4 = {(r["model"], r["condition"]): r for r in rows_of("M4_reliability.csv")}
        m5 = {(r["model"], r["condition"]): r for r in rows_of("M5_cost_latency.csv")}
        MODEL_PRETTY = {"gpt56sol": "gpt-5.6-sol", "gpt56terra": "gpt-5.6-terra",
                        "gpt56luna": "gpt-5.6-luna"}
        order = [("gpt56sol", c) for c in ("C1", "C2", "C3", "C4")] +                 [("gpt56terra", c) for c in ("C1", "C2", "C3", "C4")] +                 [("gpt56luna", c) for c in ("C1", "C2", "C3")]
        with open(GEN / "T3_model_results.tex", "w") as f:
            last_model = None
            for key in order:
                if key not in m1:
                    continue
                r1, r4, r5 = m1[key], m4.get(key, {}), m5.get(key, {})
                if last_model is not None and key[0] != last_model:
                    f.write("\\midrule\n")
                model_cell = MODEL_PRETTY[key[0]] if key[0] != last_model else ""
                last_model = key[0]
                f.write(" & ".join([
                    model_cell, key[1],
                    f"{r1['all_pass']}/{r1['cases']}",
                    f"[{float(r1['wilson_lo']):.2f}, {float(r1['wilson_hi']):.2f}]",
                    f"{float(r4.get('pass_all_k_rate', 0)):.3f}",
                    f"{float(r5.get('cost_usd', 0)):.2f}",
                    f"{float(r5.get('mean_latency_s', 0)):.0f}",
                ]) + " \\\\\n")
            f.write("\\bottomrule\n")
        # headline macros
        import json as _json
        led = _json.loads((V1 / "04_experiments" / "spend_ledger.json").read_text())
        fails = gens = 0
        for fjson in sorted((V1 / "05_results" / "model_runs").glob("P2_*.jsonl")):
            for line in open(fjson):
                d = _json.loads(line)
                if "_meta" in d or "_halt" in d:
                    continue
                gens += 1
                fails += 0 if d["result"]["all_passed"] else 1
        rep_calls = rep_unfixed = 0
        for fjson in sorted((V1 / "05_results" / "model_runs").glob("P3_*.jsonl")):
            for line in open(fjson):
                d = _json.loads(line)
                if "_meta" in d or "_halt" in d:
                    continue
                gens += 1
                rep_calls += len(d.get("repairs", []))
                rep_unfixed += 0 if d["result"]["all_passed"] else 1
        with open(GEN / "numbers.tex", "a") as f:
            f.write(f"\\newcommand{{\\PTwoGens}}{{{gens}}}\n")
            f.write(f"\\newcommand{{\\PTwoFails}}{{{fails}}}\n")
            f.write(f"\\newcommand{{\\RepairCalls}}{{{rep_calls}}}\n")
            f.write(f"\\newcommand{{\\RepairUnfixed}}{{{rep_unfixed}}}\n")
            f.write(f"\\newcommand{{\\SpendTotal}}{{{led['spent_usd']:.2f}}}\n")
    print("wrote", GEN)


if __name__ == "__main__":
    main()
